export const FETCH_POPULAR_ARTICLES = 'FETCH_POPULAR_ARTICLES';
export const FETCH_POPULAR_ARTICLES_SUCCESS = 'FETCH_POPULAR_ARTICLES_SUCCESS';
export const FETCH_POPULAR_ARTICLES_FAILURE = 'FETCH_POPULAR_ARTICLES_FAILURE';