export const FETCH_POPULAR_ARTICLES = 'FETCH_POPULAR_ARTICLES';
export const FETCH_POPULAR_ARTICLES_SUCCESS = 'FETCH_POPULAR_ARTICLES_SUCCESS';
export const FETCH_POPULAR_ARTICLES_FAILURE = 'FETCH_POPULAR_ARTICLES_FAILURE';

export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';

